#! /bin/sh
### BEGIN INIT INFO
# Provides:          lunr-api
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Example initscript
# Description:       This file should be used to construct scripts to be
#                    placed in /etc/init.d.
### END INIT INFO

# Author: Michael Barton <redbo@racklabs.com>

# Do NOT "set -e"

# PATH should only include /usr/* if it runs after the mountnfs.sh script
PATH=/sbin:/usr/sbin:/bin:/usr/bin
DESC="LUNR API Server"
SERVER=api
NAME="lunr-$SERVER"
DAEMON="/usr/bin/paster"
PIDDIR=/var/run/lunr
USER=lunr
GROUP=lunr
DAEMON_ARGS="serve /etc/lunr/$SERVER-server.conf --daemon --pid-file=$PIDDIR/$NAME.pid --user=$USER --group=$GROUP --log-file=/dev/null"
SCRIPTNAME=/etc/init.d/$NAME

# make sure the pid dir exists and is writable
mkdir -p $PIDDIR
chown -R "$USER:$GROUP" $PIDDIR

# Exit if the package is not installed
[ -x "$DAEMON" ] || exit 0

# Load the VERBOSE setting and other rcS variables
. /lib/init/vars.sh

# Define LSB log_* functions.
# Depend on lsb-base (>= 3.0-6) to ensure that this file is present.
. /lib/lsb/init-functions

case "$1" in
	start)
		$DAEMON $DAEMON_ARGS start
		;;
	stop)
		$DAEMON $DAEMON_ARGS stop
		;;
	restart)
        if $DAEMON $DAEMON_ARGS status > /dev/null ; then
            $DAEMON $DAEMON_ARGS restart
        else
            $DAEMON $DAEMON_ARGS start
        fi
	    ;;
    status)
        $DAEMON $DAEMON_ARGS status
        ;;
	*)
		echo $"Usage: $0 {start|stop|restart}"
		exit 1
esac

